# Generated by Django 4.2.2 on 2023-07-10 08:24

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_firstname_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=False, validators=[account.models.validate_terms_agreement]),
        ),
    ]
