# Generated by Django 4.2.2 on 2023-07-02 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='firstname',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Too many letters'), django.core.validators.RegexValidator('^[A-Za-z]+$', 'The text should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job_position',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50, 'You reach max length')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='lastname',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Too many letters'), django.core.validators.RegexValidator('^[A-Za-z]+$', 'The text should contain only letters.')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.MaxLengthValidator(12, message='Too many digits'), django.core.validators.RegexValidator('^\\d+$', 'The phone number should only contain digits.')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='skills',
            field=models.TextField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500, message='You reach max length')]),
        ),
        migrations.AlterField(
            model_name='employees',
            name='surname',
            field=models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30, message='Too many letters'), django.core.validators.RegexValidator('^[A-Za-z]+$', 'The text should contain only letters.')]),
        ),
    ]
