# Generated by Django 4.2.2 on 2023-07-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_address_alter_employees_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='job_position',
            field=models.CharField(choices=[('SA', 'System Administrator'), ('WD', 'Web Developer'), ('DO', 'DevOps'), ('BE', 'Backend Developer'), ('CS', 'Cyber Security'), ('NA', 'Network Administrator')], max_length=2),
        ),
    ]
