# Generated by Django 4.2.2 on 2023-07-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_companyname_company_name'),
        ('employees', '0003_alter_employees_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='base.companyname'),
        ),
    ]
