# Generated by Django 4.2.2 on 2023-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='company_name',
            field=models.CharField(help_text='Company name must be unique', max_length=60, unique=True),
        ),
    ]
